import esbuild from 'esbuild';
import process from 'process';
import { readFileSync, writeFileSync, existsSync } from 'fs';

// Node.js built-in modules (replaces deprecated 'builtin-modules' package)
const NODE_BUILTINS = [
  'assert', 'async_hooks', 'buffer', 'child_process', 'cluster', 'console',
  'constants', 'crypto', 'dgram', 'diagnostics_channel', 'dns', 'domain',
  'events', 'fs', 'http', 'http2', 'https', 'inspector', 'module', 'net',
  'os', 'path', 'perf_hooks', 'process', 'punycode', 'querystring',
  'readline', 'repl', 'stream', 'string_decoder', 'timers', 'tls',
  'trace_events', 'tty', 'url', 'util', 'v8', 'vm', 'wasi', 'worker_threads', 'zlib',
];

const prod = process.argv[2] === 'production';

// ── Embed sql.js WASM into TypeScript ──
const wasmSrc = 'node_modules/sql.js/dist/sql-wasm.wasm';
if (existsSync(wasmSrc)) {
  const wasmBuffer = readFileSync(wasmSrc);
  const base64 = wasmBuffer.toString('base64');
  // JSON.stringify handles escaping of any special chars in base64
  writeFileSync(
    'wasm-embed.ts',
    '// Auto-generated by esbuild.config.mjs — do not edit\n' +
    "import type { SqlJsStatic } from 'sql.js';\n" +
    'import initSqlJs from \'sql.js\';\n\n' +
    '/** Initialize SQL.js with embedded WASM binary (no external file needed). */\n' +
    'export async function initSqlWithWasm(): Promise<SqlJsStatic> {\n' +
    '  const binaryString = atob(' + JSON.stringify(base64) + ');\n' +
    '  const bytes = new Uint8Array(binaryString.length);\n' +
    '  for (let i = 0; i < binaryString.length; i++) {\n' +
    '    bytes[i] = binaryString.charCodeAt(i);\n' +
    '  }\n' +
    '  return initSqlJs({ wasmBinary: bytes.buffer });\n' +
    '}\n'
  );
  console.log(`Embedded sql-wasm.wasm (${(wasmBuffer.length / 1024).toFixed(0)} KB) into wasm-embed.ts`);
} else {
  console.warn('WARNING: sql-wasm.wasm not found at', wasmSrc);
}

// ── esbuild ──
const context = await esbuild.context({
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...NODE_BUILTINS,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  await context.watch();
}
